- LICENSE
> MIT Lisense

- ice-phishing/README.md
- ice-phishing/package.json
- ice-phishing/src/agent.js
- ice-phishing/src/agent.spec.js
- ice-phishing/src/helper.js
Changes:
- Update bot to raise alerts when a creator of a suspicious contract is involved in a permit/approval/transfer.
- Fix bug of the bot checking if the initiator of a transaction was a contract
- Add check for **un**verified suspicious contracts involved in a transfer
- Update tests
> Ice Phishing Bot Update

- flashloan-detector/README.md
- flashloan-detector/package-lock.json
- flashloan-detector/package.json
- flashloan-detector/src/agent.js
* Update addition method for `totalBorrowed`
* Add note to Curve Finance test transaction in `README`
> Flashloan Detector - Quick Fix

- flashloan-detector/package-lock.json
- flashloan-detector/package.json
* Increment version number in `package.json`
> FORT09.01 - Flashloan Bot Version Number Update

- flashloan-detector/README.md
- flashloan-detector/package.json
- flashloan-detector/src/agent.js
- flashloan-detector/src/agent.spec.js
- flashloan-detector/src/persistence.helper.js
- flashloan-detector/src/persistence.helper.spec.js
* Usage of `.token` property from `fetchJwt()` return value
* Update to track `totalFlashloans` instead of `totalTxns`
* Persist different values depending on current `chainId`
> FORT 09.01 - Flashloan Detector Anomaly Score & Label (Chain ID fix)

- ice-phishing/.dockerignore
- ice-phishing/.env
- ice-phishing/README.md
- ice-phishing/package-lock.json
- ice-phishing/package.json
- ice-phishing/src/agent.js
- ice-phishing/src/agent.spec.js
- ice-phishing/src/helper.js
- ice-phishing/src/persistence.helper.js
- ice-phishing/src/persistence.helper.spec.js
Changes:
- Create `persistence.helper` class for persisting values into Forta Research DB (+ add its tests)
- Add `anomalyScore` and `Labels` to `Finding`.
- Update README
> FORT09.03 - Ice Phishing Bot - Anomaly Score & Label Update

- forta-tornado-cash-starter-kit/.env
- forta-tornado-cash-starter-kit/README.md
- forta-tornado-cash-starter-kit/package-lock.json
- forta-tornado-cash-starter-kit/package.json
- forta-tornado-cash-starter-kit/src/agent.js
- forta-tornado-cash-starter-kit/src/agent.spec.js
- forta-tornado-cash-starter-kit/src/persistence.helper.js
- forta-tornado-cash-starter-kit/src/persistence.helper.spec.js
Changes:
- Create `persistence.helper` class for persisting values into Forta Research DB (+ add its tests)
- Add `anomalyScore` and `Labels` to `Finding`.
- Update README
> FORT09.04 - Tornado Cash Funded Account Contract Interaction Detector - Anomaly Score & Label Update

- flashbots-transactions-detector/.env
- flashbots-transactions-detector/README.md
- flashbots-transactions-detector/package-lock.json
- flashbots-transactions-detector/package.json
- flashbots-transactions-detector/src/agent.js
- flashbots-transactions-detector/src/agent.spec.js
- flashbots-transactions-detector/src/persistence.helper.js
- flashbots-transactions-detector/src/persistence.helper.spec.js
Add persistence, anomaly score and labels.
> FORT 09.02 - Flashbots Bot, Anomaly Score & Label Update

- flashloan-detector/README.md
- flashloan-detector/package-lock.json
- flashloan-detector/package.json
- flashloan-detector/src/agent.js
- flashloan-detector/src/agent.spec.js
- flashloan-detector/src/persistence.helper.js
- flashloan-detector/src/persistence.helper.spec.js
- Fix anomaly score
- Change "Flashloan Transaction" label to "Exploit"
> FORT 09.1.01 - Flashloan Detector Anomaly Score & Label Fix

- ice-phishing/README.md
- ice-phishing/package-lock.json
- ice-phishing/package.json
- ice-phishing/src/agent.spec.js
- ice-phishing/src/helper.js
- ice-phishing/src/persistence.helper.js
- ice-phishing/src/persistence.helper.spec.js
- Fix Anomaly score
- Change "Ice Phishing Attacker" label to "Attacker"
- Update tests
> FORT 09.1.03 - Ice Phishing Bot Anomaly Score & Label Fix

- forta-tornado-cash-starter-kit/README.md
- forta-tornado-cash-starter-kit/package-lock.json
- forta-tornado-cash-starter-kit/package.json
- forta-tornado-cash-starter-kit/src/agent.js
- forta-tornado-cash-starter-kit/src/agent.spec.js
- forta-tornado-cash-starter-kit/src/persistence.helper.js
- forta-tornado-cash-starter-kit/src/persistence.helper.spec.js
- Fix Anomaly score
- Changed the "Tornado.Cash funding recipient" label to "Attacker" and the confidence level from 1 to 0.7
> FORT09.1.04 - Tornado Cash Funded Account Bot, Anomaly Score & Label Fixes

- large-balance-decrease/README.md
- large-balance-decrease/package-lock.json
- large-balance-decrease/package.json
- large-balance-decrease/src/agent.js
- large-balance-decrease/src/agent.spec.js
- large-balance-decrease/src/persistence.helper.js
- large-balance-decrease/src/persistence.helper.spec.js
- Fix Anomaly Score
- Update "Balance Decrease Transaction" label to "Suspicious" and set the CL according to the CL of the "Victim" label of each alert (i.e. 0.7 & 0.9)
- Update `fetchJwt` method
> FORT09.1.09 - Large Balance Decrease Bot Anomaly Score & Label Update

- flashloan-detector/README.md
- flashloan-detector/package-lock.json
- flashloan-detector/package.json
- flashloan-detector/src/helper.js
This fix removes `ethers-multicall` package and replaces it with the Multicall utils in `forta-agent-tools` and enables calls for Optimism chain.
> FORT02.04 Multicall Fix for Optimism

- asset-drained/Dockerfile
- asset-drained/package-lock.json
- asset-drained/package.json
- asset-drained/src/agent-performance.spec.js
- asset-drained/src/agent.js
- ice-phishing/Dockerfile
- ice-phishing/README.md
- ice-phishing/package-lock.json
- ice-phishing/package.json
- ice-phishing/src/agent-performance.spec.js
- ice-phishing/src/agent.js
- ice-phishing/src/agent.spec.js
- ice-phishing/src/config.js
- ice-phishing/src/helper.js
- ice-phishing/src/utils.js
- Permit2
- sweep & pullToken functions
- Opensea proxy upgrade
- Performance test
> FORT01.08 + FORT01.09 + FORT20 - Ice Phishing Bot + FORT20 - Asset Drained Bot

- flashbots-transactions-detector/package-lock.json
- flashbots-transactions-detector/package.json
- flashbots-transactions-detector/src/agent.js
- flashbots-transactions-detector/src/agent.spec.js
> FORT04.04 - Flashbots Bot Update

- asset-drained/package-lock.json
- asset-drained/package.json
- asset-drained/src/agent.js
- Increases shards on Polygon & BSC
- Updates nodemon version
> FORT03.07 - Asset Drained Bot (Increase Shards)

- ice-phishing/package-lock.json
- ice-phishing/package.json
- ice-phishing/src/agent.js
- Fix issue of not assigning filtered array back to `_approvals[spender]`
> FORT01.13 - Ice Phishing (Filter Fix)

- flashloan-detector/package-lock.json
- flashloan-detector/package.json
- flashloan-detector/src/agent.js
- forta-tornado-cash-starter-kit/package-lock.json
- forta-tornado-cash-starter-kit/package.json
- forta-tornado-cash-starter-kit/src/agent.js
- large-balance-decrease/package-lock.json
- large-balance-decrease/package.json
- large-balance-decrease/src/agent.js
- large-balance-decrease/src/agent.spec.js
updated bots
- flashloan
- tc funded
- large balance decrese
> Fix for Performance Issues

- asset-drained/.gitignore
- asset-drained/package-lock.json
- asset-drained/package.json
- asset-drained/src/helper.js
* FN from [0x4f526ec20d9501c1b5137b73a704df0808f2c89bf25876d895aba14737b2ce00](https://snowtrace.io/tx/0x4f526ec20d9501c1b5137b73a704df0808f2c89bf25876d895aba14737b2ce00) txn by checking for the validity of Defi Llama response. (Accompanying issue [here](https://github.com/forta-network/starter-kits/issues/430))
> Asset Drained FNs

- flashloan-detector/Dockerfile
- flashloan-detector/package-lock.json
- flashloan-detector/package.json
- flashloan-detector/src/agent.js
- flashloan-detector/src/agent.spec.js
- flashloan-detector/src/detectors/uniswap-v2-detector.js
- flashloan-detector/src/detectors/uniswap-v3-detector.js
- flashloan-detector/src/flashloan-detector.spec.js
- flashloan-detector/src/helper.js
- flashloan-detector/src/storage.js
* [0x1274b32d4dfacd2703ad032e8bd669a83f012dde9d27ed92e4e7da0387adafe4](): Txn included `swap`ping out of the flashloaned token into the pool's other token, as well as having a new recipient EOA.
* [0x8ee76291c1b46d267431d2a528fa7f3ea7035629500bba4f87a69b88fcaf6e23](https://bscscan.com/tx/0x8ee76291c1b46d267431d2a528fa7f3ea7035629500bba4f87a69b88fcaf6e23): Txn had the PancakeSwap router send txn initiator profit BNB, which our logic handling trace processing didn't properly handle.
Addressing txns in [this issue](https://github.com/forta-network/starter-kits/issues/333).
> Flashloan FNs
